<a href="https://colab.research.google.com/github/HRashidLiaquat/PyTorch_Learning/blob/setup-test/PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introducation to tensors

# 2: Creating Tensors

In [2]:
import torch
torch.__version__


'2.9.0+cpu'

In [3]:
# 1. scalar:
scalar=torch.tensor(8)
scalar

tensor(8)

In [4]:
#Scalar has no dim is called scalar.
scalar.ndim

0

In [5]:
scalar.item()

8

In [6]:
#2 Vector provide a list
vector = torch.tensor([8,8,5,6,5])
vector



tensor([8, 8, 5, 6, 5])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([5])

In [9]:
# 3. Matrix
matrix = torch.tensor([[1, 2, 3, 4],[4, 5, 6, 5]])
matrix

tensor([[1, 2, 3, 4],
        [4, 5, 6, 5]])

In [10]:
matrix.ndim

2

In [11]:
matrix.shape

torch.Size([2, 4])

In [12]:
#4 Tensor
tensor = torch.tensor([[[1, 2, 3], [4, 5, 6], [7, 8, 9]]])
tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [13]:
tensor.ndim

3

In [14]:
tensor = torch.tensor([[[1, 2, 3,4], [4, 5, 6, 4], [7, 8, 9, 4]]])
tensor

tensor([[[1, 2, 3, 4],
         [4, 5, 6, 4],
         [7, 8, 9, 4]]])

In [15]:
tensor.ndim

3

In [16]:
tensor.shape

torch.Size([1, 3, 4])

In [17]:
#Random Tensors
random_tensor = torch.rand(10,5)
random_tensor

tensor([[0.2894, 0.3484, 0.6809, 0.5511, 0.8838],
        [0.5951, 0.9883, 0.9349, 0.4570, 0.8381],
        [0.1766, 0.3866, 0.0031, 0.4128, 0.1258],
        [0.1109, 0.4177, 0.0796, 0.1324, 0.9002],
        [0.6648, 0.1483, 0.9428, 0.4571, 0.5106],
        [0.3121, 0.9179, 0.1442, 0.7148, 0.3108],
        [0.7479, 0.8562, 0.2087, 0.8033, 0.1214],
        [0.9712, 0.3883, 0.3221, 0.5079, 0.3306],
        [0.2071, 0.3241, 0.1335, 0.7782, 0.1439],
        [0.6818, 0.7088, 0.3013, 0.1437, 0.8996]])

In [18]:
bigger_tensor = torch.rand(5,3,4)
bigger_tensor

tensor([[[0.5828, 0.2931, 0.6729, 0.7416],
         [0.0592, 0.2896, 0.8194, 0.6312],
         [0.0411, 0.4845, 0.0972, 0.0576]],

        [[0.2124, 0.8316, 0.3191, 0.8516],
         [0.6277, 0.3179, 0.9716, 0.0676],
         [0.1434, 0.9859, 0.6965, 0.4549]],

        [[0.4035, 0.2343, 0.4086, 0.7716],
         [0.6610, 0.8206, 0.3011, 0.8366],
         [0.9740, 0.5826, 0.6097, 0.5477]],

        [[0.1102, 0.8808, 0.3865, 0.5131],
         [0.2836, 0.6538, 0.3374, 0.2503],
         [0.8607, 0.4690, 0.1331, 0.4490]],

        [[0.0670, 0.7087, 0.6277, 0.3428],
         [0.1990, 0.8390, 0.4843, 0.3044],
         [0.7692, 0.7593, 0.3406, 0.7411]]])

In [19]:
#4.Zeros and Ones

In [20]:
zeros = torch.zeros(3,4)
zeros


tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [21]:
ones=torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [22]:
#5 Creating arange and tensorsors_like
x = torch.arange(1,10,2)
x

tensor([1, 3, 5, 7, 9])

In [23]:
sample = torch.arange(1,100,2)
sample


tensor([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35,
        37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67, 69, 71,
        73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [24]:
sample1 = torch.rand(3,4)
sample1

tensor([[0.9629, 0.8345, 0.8313, 0.0583],
        [0.6439, 0.7681, 0.4930, 0.9570],
        [0.2613, 0.8202, 0.7519, 0.2065]])

In [25]:
zeros_like_tensor = torch.zeros_like(sample1)
zeros_like_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [26]:
sample2 = torch.rand(3,4)
sample2

tensor([[0.0603, 0.7740, 0.3448, 0.9639],
        [0.8115, 0.6029, 0.1229, 0.5220],
        [0.0100, 0.2946, 0.7406, 0.4159]])

In [27]:
ones_like_tensor = torch.ones_like(sample1)
ones_like_tensor

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [28]:
eye= torch.eye(100)
eye

tensor([[1., 0., 0.,  ..., 0., 0., 0.],
        [0., 1., 0.,  ..., 0., 0., 0.],
        [0., 0., 1.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 1., 0., 0.],
        [0., 0., 0.,  ..., 0., 1., 0.],
        [0., 0., 0.,  ..., 0., 0., 1.]])

In [29]:
#7
full_tensor= torch.full((2,3), 20)
full_tensor

tensor([[20, 20, 20],
        [20, 20, 20]])

In [30]:
x = torch.arange(1,10,2)
x

tensor([1, 3, 5, 7, 9])

In [31]:
linear_tensor = torch.linspace(1,10,250)
linear_tensor

tensor([ 1.0000,  1.0361,  1.0723,  1.1084,  1.1446,  1.1807,  1.2169,  1.2530,
         1.2892,  1.3253,  1.3614,  1.3976,  1.4337,  1.4699,  1.5060,  1.5422,
         1.5783,  1.6145,  1.6506,  1.6867,  1.7229,  1.7590,  1.7952,  1.8313,
         1.8675,  1.9036,  1.9398,  1.9759,  2.0120,  2.0482,  2.0843,  2.1205,
         2.1566,  2.1928,  2.2289,  2.2651,  2.3012,  2.3373,  2.3735,  2.4096,
         2.4458,  2.4819,  2.5181,  2.5542,  2.5904,  2.6265,  2.6627,  2.6988,
         2.7349,  2.7711,  2.8072,  2.8434,  2.8795,  2.9157,  2.9518,  2.9880,
         3.0241,  3.0602,  3.0964,  3.1325,  3.1687,  3.2048,  3.2410,  3.2771,
         3.3133,  3.3494,  3.3855,  3.4217,  3.4578,  3.4940,  3.5301,  3.5663,
         3.6024,  3.6386,  3.6747,  3.7108,  3.7470,  3.7831,  3.8193,  3.8554,
         3.8916,  3.9277,  3.9639,  4.0000,  4.0361,  4.0723,  4.1084,  4.1446,
         4.1807,  4.2169,  4.2530,  4.2892,  4.3253,  4.3614,  4.3976,  4.4337,
         4.4699,  4.5060,  4.5422,  4.57

In [32]:
sample = torch.arange(1.,10.,2, dtype=int)
sample

tensor([1, 3, 5, 7, 9])

In [33]:
tensor_float16 = sample.type(torch.float16)
tensor_float16

tensor([1., 3., 5., 7., 9.], dtype=torch.float16)

In [34]:
tensor_int8 = sample.type(torch.int8)
tensor_int8


tensor([1, 3, 5, 7, 9], dtype=torch.int8)

In [35]:
#Getting informaction from tensor
#shape, dtype, device:

some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.9369, 0.9718, 0.0572, 0.0041],
        [0.1505, 0.0358, 0.9181, 0.5257],
        [0.4957, 0.8150, 0.8477, 0.6249]])

In [36]:
some_tensor.shape

torch.Size([3, 4])

In [37]:
some_tensor.dtype

torch.float32

In [38]:
some_tensor.device

device(type='cpu')

In [39]:
#Manipulating tensors(tensor operations)
 #1. Addition
 #2. Substraction
 #3 Multiplication
 #4 Division
 #5 Matrix multiplication


In [40]:
#Addition
tensor= torch.tensor([1,2,3])
tensor

tensor([1, 2, 3])

In [41]:
tensor + 10

tensor([11, 12, 13])

In [42]:
tensor

tensor([1, 2, 3])

In [43]:
add= tensor + 10
add

tensor([11, 12, 13])

In [44]:
tensor_a= torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])


tensor_a + tensor_b


tensor([ 6,  8, 10, 12])

In [45]:
tensor_a= torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

torch.add(tensor_a, tensor_b)

tensor([ 6,  8, 10, 12])

In [46]:
#Substraction

sub_a_tensor = torch.tensor([1,2,3,4])
sub_b_tensor = ([5,6,7,8])
sub = (sub_a_tensor - 10)
sub




tensor([-9, -8, -7, -6])

In [47]:
#Multipalcation
mul_a = torch.tensor([1,2,3,4])
mul_b = torch.tensor([5,6,7,8])
mul = mul_a * mul_b
mul

tensor([ 5, 12, 21, 32])

In [48]:
mul1 =torch.mul(mul_a, mul_b)
mul1

tensor([ 5, 12, 21, 32])

In [49]:
#Tensor division
dev_a = torch.tensor([1,2,3,4])
dev_b = torch.tensor([5,6,7,8])
dev = dev_a / dev_b
dev


tensor([0.2000, 0.3333, 0.4286, 0.5000])

In [50]:
#Tensor division
dev_a = torch.tensor([1,2,3,4])
dev_b = torch.tensor([5,6,7,8])
dev = dev_a / dev_b
dev

tensor([0.2000, 0.3333, 0.4286, 0.5000])

In [51]:
# Matrix Multiplication
matrix_a = torch.tensor([[1,2],[3,4]])
matrix_b = torch.tensor([[5,6],[7,8]])

matrix_a,matrix_b

(tensor([[1, 2],
         [3, 4]]),
 tensor([[5, 6],
         [7, 8]]))

In [52]:
matrix_a.shape,matrix_b.shape

(torch.Size([2, 2]), torch.Size([2, 2]))

In [53]:
matrix_a,matrix_b

(tensor([[1, 2],
         [3, 4]]),
 tensor([[5, 6],
         [7, 8]]))

In [54]:
matrix_a * matrix_b

tensor([[ 5, 12],
        [21, 32]])

In [55]:
matrix_a @ matrix_b

tensor([[19, 22],
        [43, 50]])

In [56]:
torch.mm(matrix_a,matrix_b)

tensor([[19, 22],
        [43, 50]])

In [57]:
torch.matmul(matrix_a, matrix_b)

tensor([[19, 22],
        [43, 50]])

In [58]:
# 6. One of the most command errors in deep learning(shape errors)
tensor_A=torch.tensor([[1, 2], [3,4],[5,6]], dtype=torch.float32)
tensor_A

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])

In [61]:
tensor_B = torch.tensor([[7,8],[9, 10],[11, 12]], dtype=torch.float32)
tensor_B

tensor([[ 7.,  8.],
        [ 9., 10.],
        [11., 12.]])

In [62]:
tensor_A @ tensor_B

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [66]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [67]:
tensor_B.T

tensor([[ 7.,  9., 11.],
        [ 8., 10., 12.]])

In [69]:
tensor_A @ tensor_B.T

tensor([[ 23.,  29.,  35.],
        [ 53.,  67.,  81.],
        [ 83., 105., 127.]])

In [51]:
# 9. findinf min, max, mean, sum etc.

In [75]:
x = torch.arange(1.,10.)
x

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [76]:
x.min()

tensor(1.)

In [77]:
x.max()

tensor(9.)

In [79]:
x.mean()

tensor(5.)

In [81]:
torch.min(x),torch.max(x),torch.sum(x),torch.mean(x)

(tensor(1.), tensor(9.), tensor(45.), tensor(5.))

In [82]:
#Positional max and min
sample= torch.arange(5,100,3)
sample

tensor([ 5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47, 50, 53, 56,
        59, 62, 65, 68, 71, 74, 77, 80, 83, 86, 89, 92, 95, 98])

In [83]:
sample.min()

tensor(5)

In [86]:
sample.argmin()

tensor(0)

In [85]:
sample.argmax()

tensor(31)