<a href="https://colab.research.google.com/github/HRashidLiaquat/PyTorch_Learning/blob/setup-test/PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introducation to tensors

# 2: Creating Tensors

In [ ]:
import torch
torch.__version__


'2.9.0+cu126'

In [ ]:
# 1. scalar:
scalar=torch.tensor(8)
scalar

0

In [ ]:
#Scalar has no dim is called scalar.
scalar.ndim

0

In [ ]:
scalar.item()

8

In [ ]:
#2 Vector provide a list
vector = torch.tensor([8,8,5,6,5])
vector



tensor([8, 8, 5, 6, 5])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([5])

In [ ]:
# 3. Matrix
matrix = torch.tensor([[1, 2, 3, 4],[4, 5, 6, 5]])
matrix

tensor([[1, 2, 3, 4],
        [4, 5, 6, 5]])

In [ ]:
matrix.ndim

2

In [ ]:
matrix.shape

torch.Size([2, 4])

In [ ]:
#4 Tensor
tensor = torch.tensor([[[1, 2, 3], [4, 5, 6], [7, 8, 9]]])
tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
tensor.ndim

3

In [ ]:
tensor = torch.tensor([[[1, 2, 3,4], [4, 5, 6, 4], [7, 8, 9, 4]]])
tensor

tensor([[[1, 2, 3, 4],
         [4, 5, 6, 4],
         [7, 8, 9, 4]]])

In [ ]:
tensor.ndim

3

In [ ]:
tensor.shape

torch.Size([1, 3, 4])

In [ ]:
#Random Tensors
random_tensor = torch.rand(10,5)
random_tensor

tensor([[0.8757, 0.0030, 0.8936, 0.5936, 0.0585],
        [0.8235, 0.7965, 0.2883, 0.4165, 0.0721],
        [0.6161, 0.9661, 0.2208, 0.9034, 0.2329],
        [0.2646, 0.5452, 0.9758, 0.5432, 0.3502],
        [0.0120, 0.3673, 0.4506, 0.5908, 0.5106],
        [0.2087, 0.4542, 0.1097, 0.0274, 0.2436],
        [0.5934, 0.0940, 0.4247, 0.2196, 0.6828],
        [0.0257, 0.5569, 0.0997, 0.5538, 0.0286],
        [0.8204, 0.5147, 0.7917, 0.7506, 0.0428],
        [0.3730, 0.9623, 0.4191, 0.9719, 0.6940]])

In [ ]:
bigger_tensor = torch.rand(5,3,4)
bigger_tensor

tensor([[[0.6778, 0.8421, 0.1728, 0.3068],
         [0.0829, 0.2051, 0.1675, 0.7756],
         [0.3419, 0.5130, 0.1619, 0.7945]],

        [[0.9557, 0.4504, 0.6182, 0.3881],
         [0.2145, 0.6398, 0.1007, 0.8761],
         [0.5244, 0.6088, 0.5587, 0.3031]],

        [[0.4244, 0.9506, 0.7536, 0.7118],
         [0.8621, 0.5531, 0.3268, 0.4922],
         [0.5480, 0.1840, 0.3476, 0.4579]],

        [[0.9911, 0.2540, 0.4142, 0.9366],
         [0.4571, 0.3963, 0.4284, 0.1423],
         [0.4226, 0.2050, 0.1659, 0.8822]],

        [[0.5713, 0.2962, 0.9998, 0.4841],
         [0.4829, 0.9606, 0.4807, 0.5788],
         [0.7498, 0.4270, 0.6333, 0.2577]]])

In [ ]:
#4.Zeros and Ones

In [ ]:
zeros = torch.zeros(3,4)
zeros


tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
ones=torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
#5 Creating arange and tensorsors_like
x = torch.arange(1,10,2)
x

tensor([1, 3, 5, 7, 9])

In [ ]:
sample = torch.arange(1,100,2)
sample


tensor([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35,
        37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67, 69, 71,
        73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [ ]:
sample1 = torch.rand(3,4)
sample1

tensor([[0.7448, 0.7924, 0.5250, 0.3916],
        [0.1300, 0.8439, 0.8948, 0.7117],
        [0.5802, 0.0087, 0.4143, 0.1535]])

In [ ]:
zeros_like_tensor = torch.zeros_like(sample1)
zeros_like_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
sample2 = torch.rand(3,4)
sample2

tensor([[0.7638, 0.9419, 0.7075, 0.6740],
        [0.8657, 0.7446, 0.8229, 0.4971],
        [0.2083, 0.3047, 0.7587, 0.6744]])

In [ ]:
ones_like_tensor = torch.ones_like(sample1)
ones_like_tensor

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
eye= torch.eye(100)
eye

tensor([[1., 0., 0.,  ..., 0., 0., 0.],
        [0., 1., 0.,  ..., 0., 0., 0.],
        [0., 0., 1.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 1., 0., 0.],
        [0., 0., 0.,  ..., 0., 1., 0.],
        [0., 0., 0.,  ..., 0., 0., 1.]])