<a href="https://colab.research.google.com/github/HRashidLiaquat/PyTorch_Learning/blob/setup-test/PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introducation to tensors

# 2: Creating Tensors

In [174]:
import torch
torch.__version__


'2.9.0+cpu'

In [175]:
# 1. scalar:
scalar=torch.tensor(8)
scalar

tensor(8)

In [176]:
#Scalar has no dim is called scalar.
scalar.ndim

0

In [177]:
scalar.item()

8

In [178]:
#2 Vector provide a list
vector = torch.tensor([8,8,5,6,5])
vector



tensor([8, 8, 5, 6, 5])

In [179]:
vector.ndim

1

In [180]:
vector.shape

torch.Size([5])

In [181]:
# 3. Matrix
matrix = torch.tensor([[1, 2, 3, 4],[4, 5, 6, 5]])
matrix

tensor([[1, 2, 3, 4],
        [4, 5, 6, 5]])

In [182]:
matrix.ndim

2

In [183]:
matrix.shape

torch.Size([2, 4])

In [184]:
#4 Tensor
tensor = torch.tensor([[[1, 2, 3], [4, 5, 6], [7, 8, 9]]])
tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [185]:
tensor.ndim

3

In [186]:
tensor = torch.tensor([[[1, 2, 3,4], [4, 5, 6, 4], [7, 8, 9, 4]]])
tensor

tensor([[[1, 2, 3, 4],
         [4, 5, 6, 4],
         [7, 8, 9, 4]]])

In [187]:
tensor.ndim

3

In [188]:
tensor.shape

torch.Size([1, 3, 4])

In [189]:
#Random Tensors
random_tensor = torch.rand(10,5)
random_tensor

tensor([[0.7639, 0.4747, 0.8365, 0.2641, 0.6018],
        [0.2520, 0.2875, 0.0642, 0.7042, 0.1518],
        [0.3068, 0.1737, 0.2343, 0.9935, 0.1876],
        [0.4605, 0.4446, 0.2049, 0.8888, 0.2813],
        [0.4433, 0.6817, 0.8282, 0.4108, 0.0415],
        [0.4616, 0.5826, 0.3217, 0.1607, 0.8377],
        [0.1724, 0.7515, 0.0761, 0.8613, 0.1074],
        [0.0239, 0.6210, 0.1927, 0.0323, 0.8161],
        [0.1163, 0.7677, 0.9109, 0.8306, 0.1898],
        [0.7370, 0.5932, 0.2926, 0.9343, 0.9443]])

In [190]:
bigger_tensor = torch.rand(5,3,4)
bigger_tensor

tensor([[[0.3591, 0.9216, 0.1747, 0.2887],
         [0.0563, 0.5465, 0.0971, 0.5759],
         [0.2475, 0.4454, 0.5325, 0.3635]],

        [[0.7156, 0.8985, 0.7453, 0.3142],
         [0.1437, 0.5844, 0.4902, 0.4997],
         [0.3616, 0.0323, 0.5063, 0.9914]],

        [[0.7472, 0.3291, 0.5215, 0.2133],
         [0.6148, 0.7201, 0.5104, 0.6153],
         [0.5775, 0.1985, 0.4738, 0.2540]],

        [[0.7030, 0.3476, 0.4316, 0.9202],
         [0.1946, 0.6423, 0.1751, 0.3343],
         [0.3367, 0.1095, 0.1845, 0.2625]],

        [[0.5146, 0.2593, 0.8426, 0.7921],
         [0.7215, 0.4462, 0.2160, 0.0372],
         [0.9676, 0.1974, 0.2666, 0.8328]]])

In [191]:
#4.Zeros and Ones

In [192]:
zeros = torch.zeros(3,4)
zeros


tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [193]:
ones=torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [194]:
#5 Creating arange and tensorsors_like
x = torch.arange(1,10,2)
x

tensor([1, 3, 5, 7, 9])

In [195]:
sample = torch.arange(1,100,2)
sample


tensor([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35,
        37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67, 69, 71,
        73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [196]:
sample1 = torch.rand(3,4)
sample1

tensor([[0.3205, 0.8697, 0.1140, 0.1324],
        [0.1854, 0.1336, 0.7801, 0.3643],
        [0.8903, 0.5464, 0.4468, 0.8917]])

In [197]:
zeros_like_tensor = torch.zeros_like(sample1)
zeros_like_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [198]:
sample2 = torch.rand(3,4)
sample2

tensor([[0.7298, 0.8777, 0.1152, 0.6703],
        [0.8581, 0.3552, 0.5170, 0.2077],
        [0.5241, 0.1703, 0.1515, 0.3853]])

In [199]:
ones_like_tensor = torch.ones_like(sample1)
ones_like_tensor

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [200]:
eye= torch.eye(100)
eye

tensor([[1., 0., 0.,  ..., 0., 0., 0.],
        [0., 1., 0.,  ..., 0., 0., 0.],
        [0., 0., 1.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 1., 0., 0.],
        [0., 0., 0.,  ..., 0., 1., 0.],
        [0., 0., 0.,  ..., 0., 0., 1.]])

In [201]:
#7
full_tensor= torch.full((2,3), 20)
full_tensor

tensor([[20, 20, 20],
        [20, 20, 20]])

In [202]:
x = torch.arange(1,10,2)
x

tensor([1, 3, 5, 7, 9])

In [203]:
linear_tensor = torch.linspace(1,10,250)
linear_tensor

tensor([ 1.0000,  1.0361,  1.0723,  1.1084,  1.1446,  1.1807,  1.2169,  1.2530,
         1.2892,  1.3253,  1.3614,  1.3976,  1.4337,  1.4699,  1.5060,  1.5422,
         1.5783,  1.6145,  1.6506,  1.6867,  1.7229,  1.7590,  1.7952,  1.8313,
         1.8675,  1.9036,  1.9398,  1.9759,  2.0120,  2.0482,  2.0843,  2.1205,
         2.1566,  2.1928,  2.2289,  2.2651,  2.3012,  2.3373,  2.3735,  2.4096,
         2.4458,  2.4819,  2.5181,  2.5542,  2.5904,  2.6265,  2.6627,  2.6988,
         2.7349,  2.7711,  2.8072,  2.8434,  2.8795,  2.9157,  2.9518,  2.9880,
         3.0241,  3.0602,  3.0964,  3.1325,  3.1687,  3.2048,  3.2410,  3.2771,
         3.3133,  3.3494,  3.3855,  3.4217,  3.4578,  3.4940,  3.5301,  3.5663,
         3.6024,  3.6386,  3.6747,  3.7108,  3.7470,  3.7831,  3.8193,  3.8554,
         3.8916,  3.9277,  3.9639,  4.0000,  4.0361,  4.0723,  4.1084,  4.1446,
         4.1807,  4.2169,  4.2530,  4.2892,  4.3253,  4.3614,  4.3976,  4.4337,
         4.4699,  4.5060,  4.5422,  4.57

In [204]:
sample = torch.arange(1.,10.,2, dtype=int)
sample

tensor([1, 3, 5, 7, 9])

In [205]:
tensor_float16 = sample.type(torch.float16)
tensor_float16

tensor([1., 3., 5., 7., 9.], dtype=torch.float16)

In [206]:
tensor_int8 = sample.type(torch.int8)
tensor_int8


tensor([1, 3, 5, 7, 9], dtype=torch.int8)

In [207]:
#Getting informaction from tensor
#shape, dtype, device:

some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.6240, 0.0540, 0.8236, 0.5067],
        [0.5330, 0.7317, 0.4710, 0.2691],
        [0.9515, 0.9732, 0.1985, 0.6750]])

In [208]:
some_tensor.shape

torch.Size([3, 4])

In [209]:
some_tensor.dtype

torch.float32

In [210]:
some_tensor.device

device(type='cpu')

In [211]:
#Manipulating tensors(tensor operations)
 #1. Addition
 #2. Substraction
 #3 Multiplication
 #4 Division
 #5 Matrix multiplication


In [212]:
#Addition
tensor= torch.tensor([1,2,3])
tensor

tensor([1, 2, 3])

In [213]:
tensor + 10

tensor([11, 12, 13])

In [214]:
tensor

tensor([1, 2, 3])

In [215]:
add= tensor + 10
add

tensor([11, 12, 13])

In [216]:
tensor_a= torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])


tensor_a + tensor_b


tensor([ 6,  8, 10, 12])

In [217]:
tensor_a= torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

torch.add(tensor_a, tensor_b)

tensor([ 6,  8, 10, 12])

In [218]:
#Substraction

sub_a_tensor = torch.tensor([1,2,3,4])
sub_b_tensor = ([5,6,7,8])
sub = (sub_a_tensor - 10)
sub




tensor([-9, -8, -7, -6])

In [219]:
#Multipalcation
mul_a = torch.tensor([1,2,3,4])
mul_b = torch.tensor([5,6,7,8])
mul = mul_a * mul_b
mul

tensor([ 5, 12, 21, 32])

In [220]:
mul1 =torch.mul(mul_a, mul_b)
mul1

tensor([ 5, 12, 21, 32])

In [221]:
#Tensor division
dev_a = torch.tensor([1,2,3,4])
dev_b = torch.tensor([5,6,7,8])
dev = dev_a / dev_b
dev


tensor([0.2000, 0.3333, 0.4286, 0.5000])

In [222]:
#Tensor division
dev_a = torch.tensor([1,2,3,4])
dev_b = torch.tensor([5,6,7,8])
dev = dev_a / dev_b
dev

tensor([0.2000, 0.3333, 0.4286, 0.5000])

In [223]:
# Matrix Multiplication
matrix_a = torch.tensor([[1,2],[3,4]])
matrix_b = torch.tensor([[5,6],[7,8]])

matrix_a,matrix_b

(tensor([[1, 2],
         [3, 4]]),
 tensor([[5, 6],
         [7, 8]]))

In [224]:
matrix_a.shape,matrix_b.shape

(torch.Size([2, 2]), torch.Size([2, 2]))

In [225]:
matrix_a,matrix_b

(tensor([[1, 2],
         [3, 4]]),
 tensor([[5, 6],
         [7, 8]]))

In [226]:
matrix_a * matrix_b

tensor([[ 5, 12],
        [21, 32]])

In [227]:
matrix_a @ matrix_b

tensor([[19, 22],
        [43, 50]])

In [228]:
torch.mm(matrix_a,matrix_b)

tensor([[19, 22],
        [43, 50]])

In [229]:
torch.matmul(matrix_a, matrix_b)

tensor([[19, 22],
        [43, 50]])

In [230]:
# 6. One of the most command errors in deep learning(shape errors)
tensor_A=torch.tensor([[1, 2], [3,4],[5,6]], dtype=torch.float32)
tensor_A

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])

In [231]:
tensor_B = torch.tensor([[7,8],[9, 10],[11, 12]], dtype=torch.float32)
tensor_B

tensor([[ 7.,  8.],
        [ 9., 10.],
        [11., 12.]])

In [233]:
tensor_A @ tensor_B

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [234]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [235]:
tensor_B.T

tensor([[ 7.,  9., 11.],
        [ 8., 10., 12.]])

In [ ]:
tensor_A @ tensor_B.T

In [ ]:
# 9. findinf min, max, mean, sum etc.

In [236]:
x = torch.arange(1.,10.)
x

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
x.min()

In [ ]:
x.max()

In [ ]:
x.mean()

In [ ]:
torch.min(x),torch.max(x),torch.sum(x),torch.mean(x)

In [ ]:
#Positional max and min
sample= torch.arange(5,100,3)
sample

In [ ]:
sample.min()

In [ ]:
sample.argmin()

In [ ]:
sample.argmax()

In [237]:
#To reshaping, stacking, squeezing, unsqeeze,permute
x = torch.arange(1.,101.)
x

tensor([  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,  12.,
         13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,  22.,  23.,  24.,
         25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,  33.,  34.,  35.,  36.,
         37.,  38.,  39.,  40.,  41.,  42.,  43.,  44.,  45.,  46.,  47.,  48.,
         49.,  50.,  51.,  52.,  53.,  54.,  55.,  56.,  57.,  58.,  59.,  60.,
         61.,  62.,  63.,  64.,  65.,  66.,  67.,  68.,  69.,  70.,  71.,  72.,
         73.,  74.,  75.,  76.,  77.,  78.,  79.,  80.,  81.,  82.,  83.,  84.,
         85.,  86.,  87.,  88.,  89.,  90.,  91.,  92.,  93.,  94.,  95.,  96.,
         97.,  98.,  99., 100.])

In [238]:
x_reshaped = x.reshape(10,10)
x_reshaped

tensor([[  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.],
        [ 11.,  12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.],
        [ 21.,  22.,  23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.],
        [ 31.,  32.,  33.,  34.,  35.,  36.,  37.,  38.,  39.,  40.],
        [ 41.,  42.,  43.,  44.,  45.,  46.,  47.,  48.,  49.,  50.],
        [ 51.,  52.,  53.,  54.,  55.,  56.,  57.,  58.,  59.,  60.],
        [ 61.,  62.,  63.,  64.,  65.,  66.,  67.,  68.,  69.,  70.],
        [ 71.,  72.,  73.,  74.,  75.,  76.,  77.,  78.,  79.,  80.],
        [ 81.,  82.,  83.,  84.,  85.,  86.,  87.,  88.,  89.,  90.],
        [ 91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,  99., 100.]])

In [239]:
#View
view_tensor = torch.arange(1.,9.)
view_tensor

tensor([1., 2., 3., 4., 5., 6., 7., 8.])

In [240]:
view_tensor

tensor([1., 2., 3., 4., 5., 6., 7., 8.])

In [241]:
view=view_tensor.view(2,4)
view

tensor([[1., 2., 3., 4.],
        [5., 6., 7., 8.]])

In [244]:
view[0,0] = 5
view

tensor([[5., 2., 3., 4.],
        [5., 6., 7., 8.]])

In [245]:
#Stacking
tensor = torch.arange(1.,8.)
tensor

tensor([1., 2., 3., 4., 5., 6., 7.])

In [246]:
stacking_tensor = torch.stack([tensor,tensor,tensor,tensor], dim=1)
stacking_tensor

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.]])

In [247]:
stacking_tensor = torch.stack([tensor,tensor,tensor], dim = 0)
stacking_tensor

tensor([[1., 2., 3., 4., 5., 6., 7.],
        [1., 2., 3., 4., 5., 6., 7.],
        [1., 2., 3., 4., 5., 6., 7.]])

In [248]:
view

tensor([[5., 2., 3., 4.],
        [5., 6., 7., 8.]])

In [249]:
# torch unsqueeze
x = x = torch.arange(1.,8.)
x

tensor([1., 2., 3., 4., 5., 6., 7.])

In [250]:
x.shape, x.ndim

(torch.Size([7]), 1)

In [253]:
x_unsqueez = x.unsqueeze(dim=0)
x_unsqueez.shape, x_unsqueez.ndim

(torch.Size([1, 7]), 2)

In [254]:
x_unsqueez.shape

torch.Size([1, 7])

In [255]:
x_squeez = x_unsqueez.squeeze()
x_squeez


tensor([1., 2., 3., 4., 5., 6., 7.])

In [256]:
x_squeez.shape

torch.Size([7])

In [257]:
#permute
x = torch.rand(2,3,5)
x

tensor([[[0.4027, 0.8766, 0.2816, 0.5802, 0.2960],
         [0.2969, 0.7085, 0.3171, 0.5664, 0.9682],
         [0.8495, 0.6840, 0.6749, 0.1044, 0.3597]],

        [[0.2083, 0.2935, 0.0186, 0.0977, 0.0505],
         [0.5552, 0.3637, 0.2159, 0.3589, 0.5811],
         [0.6538, 0.8305, 0.0222, 0.7377, 0.6209]]])

In [258]:
x.shape,x.ndim

(torch.Size([2, 3, 5]), 3)