<a href="https://colab.research.google.com/github/HRashidLiaquat/PyTorch_Learning/blob/setup-test/PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introducation to tensors

# 2: Creating Tensors

In [2]:
import torch
torch.__version__


'2.9.0+cu126'

In [3]:
# 1. scalar:
scalar=torch.tensor(8)
scalar

tensor(8)

In [4]:
#Scalar has no dim is called scalar.
scalar.ndim

0

In [5]:
scalar.item()

8

In [6]:
#2 Vector provide a list
vector = torch.tensor([8,8,5,6,5])
vector



tensor([8, 8, 5, 6, 5])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([5])

In [9]:
# 3. Matrix
matrix = torch.tensor([[1, 2, 3, 4],[4, 5, 6, 5]])
matrix

tensor([[1, 2, 3, 4],
        [4, 5, 6, 5]])

In [10]:
matrix.ndim

2

In [11]:
matrix.shape

torch.Size([2, 4])

In [12]:
#4 Tensor
tensor = torch.tensor([[[1, 2, 3], [4, 5, 6], [7, 8, 9]]])
tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [13]:
tensor.ndim

3

In [14]:
tensor = torch.tensor([[[1, 2, 3,4], [4, 5, 6, 4], [7, 8, 9, 4]]])
tensor

tensor([[[1, 2, 3, 4],
         [4, 5, 6, 4],
         [7, 8, 9, 4]]])

In [15]:
tensor.ndim

3

In [16]:
tensor.shape

torch.Size([1, 3, 4])

In [17]:
#Random Tensors
random_tensor = torch.rand(10,5)
random_tensor

tensor([[0.9059, 0.1557, 0.0299, 0.2249, 0.0177],
        [0.6898, 0.7827, 0.9481, 0.7846, 0.4592],
        [0.1211, 0.0751, 0.5568, 0.3409, 0.1534],
        [0.7228, 0.9098, 0.0519, 0.3170, 0.4369],
        [0.6711, 0.2619, 0.9195, 0.7130, 0.4205],
        [0.8980, 0.8946, 0.7562, 0.7210, 0.1773],
        [0.7958, 0.2758, 0.0569, 0.1064, 0.7238],
        [0.9720, 0.7149, 0.1500, 0.3534, 0.4463],
        [0.0744, 0.6462, 0.0455, 0.6060, 0.0070],
        [0.4724, 0.6514, 0.0676, 0.9830, 0.9079]])

In [18]:
bigger_tensor = torch.rand(5,3,4)
bigger_tensor

tensor([[[0.6853, 0.5158, 0.4152, 0.4856],
         [0.4688, 0.6698, 0.9757, 0.8301],
         [0.6899, 0.5699, 0.3309, 0.9064]],

        [[0.7417, 0.7535, 0.0922, 0.5803],
         [0.6019, 0.9514, 0.2788, 0.6073],
         [0.2946, 0.7859, 0.5178, 0.2133]],

        [[0.3468, 0.8581, 0.1140, 0.9555],
         [0.8777, 0.0391, 0.9761, 0.5007],
         [0.5091, 0.1022, 0.1976, 0.2802]],

        [[0.9228, 0.3001, 0.2582, 0.2809],
         [0.0870, 0.6582, 0.3409, 0.7767],
         [0.4694, 0.7217, 0.3403, 0.5376]],

        [[0.1507, 0.4417, 0.2385, 0.4451],
         [0.7706, 0.0887, 0.7995, 0.9096],
         [0.2149, 0.8050, 0.4849, 0.2002]]])

In [19]:
#4.Zeros and Ones

In [20]:
zeros = torch.zeros(3,4)
zeros


tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [21]:
ones=torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [22]:
#5 Creating arange and tensorsors_like
x = torch.arange(1,10,2)
x

tensor([1, 3, 5, 7, 9])

In [23]:
sample = torch.arange(1,100,2)
sample


tensor([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35,
        37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67, 69, 71,
        73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [24]:
sample1 = torch.rand(3,4)
sample1

tensor([[0.7234, 0.7665, 0.6493, 0.6458],
        [0.3494, 0.1085, 0.2211, 0.3875],
        [0.4249, 0.8597, 0.4472, 0.9495]])

In [25]:
zeros_like_tensor = torch.zeros_like(sample1)
zeros_like_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [26]:
sample2 = torch.rand(3,4)
sample2

tensor([[0.7709, 0.8345, 0.5421, 0.2235],
        [0.7694, 0.9785, 0.6733, 0.3421],
        [0.5177, 0.1740, 0.1618, 0.2509]])

In [27]:
ones_like_tensor = torch.ones_like(sample1)
ones_like_tensor

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [28]:
eye= torch.eye(100)
eye

tensor([[1., 0., 0.,  ..., 0., 0., 0.],
        [0., 1., 0.,  ..., 0., 0., 0.],
        [0., 0., 1.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 1., 0., 0.],
        [0., 0., 0.,  ..., 0., 1., 0.],
        [0., 0., 0.,  ..., 0., 0., 1.]])

In [29]:
#7
full_tensor= torch.full((2,3), 20)
full_tensor

tensor([[20, 20, 20],
        [20, 20, 20]])

In [30]:
x = torch.arange(1,10,2)
x

tensor([1, 3, 5, 7, 9])

In [31]:
linear_tensor = torch.linspace(1,10,250)
linear_tensor

tensor([ 1.0000,  1.0361,  1.0723,  1.1084,  1.1446,  1.1807,  1.2169,  1.2530,
         1.2892,  1.3253,  1.3614,  1.3976,  1.4337,  1.4699,  1.5060,  1.5422,
         1.5783,  1.6145,  1.6506,  1.6867,  1.7229,  1.7590,  1.7952,  1.8313,
         1.8675,  1.9036,  1.9398,  1.9759,  2.0120,  2.0482,  2.0843,  2.1205,
         2.1566,  2.1928,  2.2289,  2.2651,  2.3012,  2.3373,  2.3735,  2.4096,
         2.4458,  2.4819,  2.5181,  2.5542,  2.5904,  2.6265,  2.6627,  2.6988,
         2.7349,  2.7711,  2.8072,  2.8434,  2.8795,  2.9157,  2.9518,  2.9880,
         3.0241,  3.0602,  3.0964,  3.1325,  3.1687,  3.2048,  3.2410,  3.2771,
         3.3133,  3.3494,  3.3855,  3.4217,  3.4578,  3.4940,  3.5301,  3.5663,
         3.6024,  3.6386,  3.6747,  3.7108,  3.7470,  3.7831,  3.8193,  3.8554,
         3.8916,  3.9277,  3.9639,  4.0000,  4.0361,  4.0723,  4.1084,  4.1446,
         4.1807,  4.2169,  4.2530,  4.2892,  4.3253,  4.3614,  4.3976,  4.4337,
         4.4699,  4.5060,  4.5422,  4.57

In [32]:
sample = torch.arange(1.,10.,2, dtype=int)
sample

tensor([1, 3, 5, 7, 9])

In [33]:
tensor_float16 = sample.type(torch.float16)
tensor_float16

tensor([1., 3., 5., 7., 9.], dtype=torch.float16)

In [34]:
tensor_int8 = sample.type(torch.int8)
tensor_int8


tensor([1, 3, 5, 7, 9], dtype=torch.int8)

In [35]:
#Getting informaction from tensor
#shape, dtype, device:

some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.7677, 0.8007, 0.4832, 0.9378],
        [0.1553, 0.2020, 0.8870, 0.6541],
        [0.6452, 0.7287, 0.0372, 0.8442]])

In [36]:
some_tensor.shape

torch.Size([3, 4])

In [37]:
some_tensor.dtype

torch.float32

In [38]:
some_tensor.device

device(type='cpu')

In [39]:
#Manipulating tensors(tensor operations)
 #1. Addition
 #2. Substraction
 #3 Multiplication
 #4 Division
 #5 Matrix multiplication


In [40]:
#Addition
tensor= torch.tensor([1,2,3])
tensor

tensor([1, 2, 3])

In [41]:
tensor + 10

tensor([11, 12, 13])

In [42]:
tensor

tensor([1, 2, 3])

In [43]:
add= tensor + 10
add

tensor([11, 12, 13])

In [44]:
tensor_a= torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])


tensor_a + tensor_b


tensor([ 6,  8, 10, 12])

In [45]:
tensor_a= torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

torch.add(tensor_a, tensor_b)

tensor([ 6,  8, 10, 12])

In [46]:
#Substraction

sub_a_tensor = torch.tensor([1,2,3,4])
sub_b_tensor = ([5,6,7,8])
sub = (sub_a_tensor - 10)
sub




tensor([-9, -8, -7, -6])

In [47]:
#Multipalcation
mul_a = torch.tensor([1,2,3,4])
mul_b = torch.tensor([5,6,7,8])
mul = mul_a * mul_b
mul

tensor([ 5, 12, 21, 32])

In [48]:
mul1 =torch.mul(mul_a, mul_b)
mul1

tensor([ 5, 12, 21, 32])

In [49]:
#Tensor division
dev_a = torch.tensor([1,2,3,4])
dev_b = torch.tensor([5,6,7,8])
dev = dev_a / dev_b
dev


tensor([0.2000, 0.3333, 0.4286, 0.5000])

In [50]:
#Tensor division
dev_a = torch.tensor([1,2,3,4])
dev_b = torch.tensor([5,6,7,8])
dev = dev_a / dev_b
dev

tensor([0.2000, 0.3333, 0.4286, 0.5000])

In [51]:
# Matrix Multiplication
matrix_a = torch.tensor([[1,2],[3,4]])
matrix_b = torch.tensor([[5,6],[7,8]])

matrix_a,matrix_b

(tensor([[1, 2],
         [3, 4]]),
 tensor([[5, 6],
         [7, 8]]))

In [52]:
matrix_a.shape,matrix_b.shape

(torch.Size([2, 2]), torch.Size([2, 2]))

In [53]:
matrix_a,matrix_b

(tensor([[1, 2],
         [3, 4]]),
 tensor([[5, 6],
         [7, 8]]))

In [54]:
matrix_a * matrix_b

tensor([[ 5, 12],
        [21, 32]])

In [55]:
matrix_a @ matrix_b

tensor([[19, 22],
        [43, 50]])

In [56]:
torch.mm(matrix_a,matrix_b)

tensor([[19, 22],
        [43, 50]])

In [57]:
torch.matmul(matrix_a, matrix_b)

tensor([[19, 22],
        [43, 50]])

In [58]:
# 6. One of the most command errors in deep learning(shape errors)
tensor_A=torch.tensor([[1, 2], [3,4],[5,6]], dtype=torch.float32)
tensor_A

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])

In [59]:
tensor_B = torch.tensor([[7,8],[9, 10],[11, 12]], dtype=torch.float32)
tensor_B

tensor([[ 7.,  8.],
        [ 9., 10.],
        [11., 12.]])

In [60]:
tensor_A @ tensor_B

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
tensor_A.shape, tensor_B.shape

In [ ]:
tensor_B.T

In [ ]:
tensor_A @ tensor_B.T

In [ ]:
# 9. findinf min, max, mean, sum etc.

In [ ]:
x = torch.arange(1.,10.)
x

In [ ]:
x.min()

In [ ]:
x.max()

In [ ]:
x.mean()

In [ ]:
torch.min(x),torch.max(x),torch.sum(x),torch.mean(x)

In [ ]:
#Positional max and min
sample= torch.arange(5,100,3)
sample

In [ ]:
sample.min()

In [ ]:
sample.argmin()

In [ ]:
sample.argmax()

In [ ]:
#To reshaping, stacking, squeezing, unsqeeze,permute
x = torch.arange(1.,101.)
x

In [ ]:
x_reshaped = x.reshape(10,10)
x_reshaped

In [ ]:
#View
view_tensor = torch.arange(1.,9.)
view_tensor

In [ ]:
view_tensor

In [ ]:
view=view_tensor.view(2,4)
view

In [ ]:
view[0,0] = 5
view

In [ ]:
#Stacking
tensor = torch.arange(1.,8.)
tensor

In [ ]:
stacking_tensor = torch.stack([tensor,tensor,tensor,tensor], dim=1)
stacking_tensor

In [ ]:
stacking_tensor = torch.stack([tensor,tensor,tensor], dim = 0)
stacking_tensor

In [ ]:
view

In [ ]:
# torch unsqueeze
x = x = torch.arange(1.,8.)
x

In [ ]:
x.shape, x.ndim

In [ ]:
x_unsqueez = x.unsqueeze(dim=0)
x_unsqueez.shape, x_unsqueez.ndim

In [ ]:
x_unsqueez.shape

In [ ]:
x_squeez = x_unsqueez.squeeze()
x_squeez


In [ ]:
x_squeez.shape

In [ ]:
#permute
x = torch.rand(2,3,5)
x

In [ ]:
x.shape,x.ndim

In [ ]:
x.shape

In [ ]:
x_permuted = x.permute(2,1,0)
x_permuted

In [ ]:
x_permuted.shape

In [ ]:
#Indexing in pythorch
x = torch.arange(1,10).reshape(1,3,3)
x

In [ ]:
x.shape

In [ ]:
x[0]

In [ ]:
x[0,0]

In [ ]:
x[0,2,2]

In [ ]:
x[0,0,0]

In [ ]:
x[0,0,2]

In [ ]:
x[0,1,2]

# **12. PyTorch tensors and Numpy**

In [ ]:
import numpy as np

In [ ]:
array= np.arange(1.0,8.0)
array

In [ ]:
tensor = torch.from_numpy(array)
tensor

In [ ]:
numpy_array = tensor.numpy()
numpy_array

In [ ]:
array, tensor,numpy_array

# **13:Reproaucibillty **

In [ ]:
random_tensor_A=torch.rand(3,4)
random_tensor_A

In [ ]:
random_tensor_B= torch.rand(3,4)
random_tensor_B

In [ ]:
random_seed= 42
torch.manual_seed(random_seed)
random_tensor_c=torch.rand(3,4)
random_tensor_c

In [ ]:
torch.manual_seed(42)
random_tensor_d=torch.rand(3,4)
random_tensor_d

In [61]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [62]:
torch.cuda.device_count()

1

In [63]:
tensor= torch.tensor([1,2,3])
tensor

tensor([1, 2, 3])

In [64]:
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [65]:
tensor_on_gpu=tensor.to(device)
tensor_on_gpu,tensor_on_gpu.device

(tensor([1, 2, 3], device='cuda:0'), device(type='cuda', index=0))

In [66]:
tensor_back_on_cpu=tensor_on_gpu.cpu()
tensor_back_on_cpu.device

device(type='cpu')