<a href="https://colab.research.google.com/github/HRashidLiaquat/PyTorch_Learning/blob/setup-test/PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introducation to tensors

# 2: Creating Tensors

In [186]:
import torch
torch.__version__


'2.9.0+cu126'

In [187]:
# 1. scalar:
scalar=torch.tensor(8)
scalar

tensor(8)

In [188]:
#Scalar has no dim is called scalar.
scalar.ndim

0

In [189]:
scalar.item()

8

In [190]:
#2 Vector provide a list
vector = torch.tensor([8,8,5,6,5])
vector



tensor([8, 8, 5, 6, 5])

In [191]:
vector.ndim

1

In [192]:
vector.shape

torch.Size([5])

In [193]:
# 3. Matrix
matrix = torch.tensor([[1, 2, 3, 4],[4, 5, 6, 5]])
matrix

tensor([[1, 2, 3, 4],
        [4, 5, 6, 5]])

In [194]:
matrix.ndim

2

In [195]:
matrix.shape

torch.Size([2, 4])

In [196]:
#4 Tensor
tensor = torch.tensor([[[1, 2, 3], [4, 5, 6], [7, 8, 9]]])
tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [197]:
tensor.ndim

3

In [198]:
tensor = torch.tensor([[[1, 2, 3,4], [4, 5, 6, 4], [7, 8, 9, 4]]])
tensor

tensor([[[1, 2, 3, 4],
         [4, 5, 6, 4],
         [7, 8, 9, 4]]])

In [199]:
tensor.ndim

3

In [200]:
tensor.shape

torch.Size([1, 3, 4])

In [201]:
#Random Tensors
random_tensor = torch.rand(10,5)
random_tensor

tensor([[0.2089, 0.6659, 0.0888, 0.8483, 0.1001],
        [0.5655, 0.3324, 0.9352, 0.0163, 0.7379],
        [0.8502, 0.2908, 0.8761, 0.5941, 0.8712],
        [0.5198, 0.9299, 0.6847, 0.0663, 0.4190],
        [0.9459, 0.7806, 0.0835, 0.5672, 0.6663],
        [0.7497, 0.3860, 0.1966, 0.9812, 0.7403],
        [0.8013, 0.8231, 0.1139, 0.9892, 0.4727],
        [0.5370, 0.7638, 0.1102, 0.4489, 0.7503],
        [0.8594, 0.6535, 0.2777, 0.2682, 0.8588],
        [0.3767, 0.4378, 0.9108, 0.6224, 0.2751]])

In [202]:
bigger_tensor = torch.rand(5,3,4)
bigger_tensor

tensor([[[0.0056, 0.4508, 0.1717, 0.1806],
         [0.1006, 0.8650, 0.8541, 0.6256],
         [0.1349, 0.5613, 0.4902, 0.6297]],

        [[0.8075, 0.1293, 0.3368, 0.2910],
         [0.4463, 0.8267, 0.6096, 0.0830],
         [0.8954, 0.0352, 0.3776, 0.3070]],

        [[0.8911, 0.1308, 0.6918, 0.3774],
         [0.1494, 0.5718, 0.4981, 0.5033],
         [0.0903, 0.3544, 0.4946, 0.1063]],

        [[0.3331, 0.1167, 0.0473, 0.7351],
         [0.3772, 0.3603, 0.4006, 0.4288],
         [0.9729, 0.7503, 0.1253, 0.2992]],

        [[0.2281, 0.6483, 0.4113, 0.9133],
         [0.6555, 0.6110, 0.9209, 0.5582],
         [0.3350, 0.6267, 0.0273, 0.7642]]])

In [203]:
#4.Zeros and Ones

In [204]:
zeros = torch.zeros(3,4)
zeros


tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [205]:
ones=torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [206]:
#5 Creating arange and tensorsors_like
x = torch.arange(1,10,2)
x

tensor([1, 3, 5, 7, 9])

In [207]:
sample = torch.arange(1,100,2)
sample


tensor([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35,
        37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67, 69, 71,
        73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [208]:
sample1 = torch.rand(3,4)
sample1

tensor([[0.6595, 0.1845, 0.1501, 0.4183],
        [0.2201, 0.6699, 0.1991, 0.0461],
        [0.5581, 0.1236, 0.1418, 0.6707]])

In [209]:
zeros_like_tensor = torch.zeros_like(sample1)
zeros_like_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [210]:
sample2 = torch.rand(3,4)
sample2

tensor([[0.3167, 0.2391, 0.9821, 0.9462],
        [0.9112, 0.1183, 0.5075, 0.7153],
        [0.2156, 0.3989, 0.8044, 0.1816]])

In [211]:
ones_like_tensor = torch.ones_like(sample1)
ones_like_tensor

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [212]:
eye= torch.eye(100)
eye

tensor([[1., 0., 0.,  ..., 0., 0., 0.],
        [0., 1., 0.,  ..., 0., 0., 0.],
        [0., 0., 1.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 1., 0., 0.],
        [0., 0., 0.,  ..., 0., 1., 0.],
        [0., 0., 0.,  ..., 0., 0., 1.]])

In [213]:
#7
full_tensor= torch.full((2,3), 20)
full_tensor

tensor([[20, 20, 20],
        [20, 20, 20]])

In [214]:
x = torch.arange(1,10,2)
x

tensor([1, 3, 5, 7, 9])

In [215]:
linear_tensor = torch.linspace(1,10,250)
linear_tensor

tensor([ 1.0000,  1.0361,  1.0723,  1.1084,  1.1446,  1.1807,  1.2169,  1.2530,
         1.2892,  1.3253,  1.3614,  1.3976,  1.4337,  1.4699,  1.5060,  1.5422,
         1.5783,  1.6145,  1.6506,  1.6867,  1.7229,  1.7590,  1.7952,  1.8313,
         1.8675,  1.9036,  1.9398,  1.9759,  2.0120,  2.0482,  2.0843,  2.1205,
         2.1566,  2.1928,  2.2289,  2.2651,  2.3012,  2.3373,  2.3735,  2.4096,
         2.4458,  2.4819,  2.5181,  2.5542,  2.5904,  2.6265,  2.6627,  2.6988,
         2.7349,  2.7711,  2.8072,  2.8434,  2.8795,  2.9157,  2.9518,  2.9880,
         3.0241,  3.0602,  3.0964,  3.1325,  3.1687,  3.2048,  3.2410,  3.2771,
         3.3133,  3.3494,  3.3855,  3.4217,  3.4578,  3.4940,  3.5301,  3.5663,
         3.6024,  3.6386,  3.6747,  3.7108,  3.7470,  3.7831,  3.8193,  3.8554,
         3.8916,  3.9277,  3.9639,  4.0000,  4.0361,  4.0723,  4.1084,  4.1446,
         4.1807,  4.2169,  4.2530,  4.2892,  4.3253,  4.3614,  4.3976,  4.4337,
         4.4699,  4.5060,  4.5422,  4.57

In [216]:
sample = torch.arange(1.,10.,2, dtype=int)
sample

tensor([1, 3, 5, 7, 9])

In [217]:
tensor_float16 = sample.type(torch.float16)
tensor_float16

tensor([1., 3., 5., 7., 9.], dtype=torch.float16)

In [218]:
tensor_int8 = sample.type(torch.int8)
tensor_int8


tensor([1, 3, 5, 7, 9], dtype=torch.int8)

In [219]:
#Getting informaction from tensor
#shape, dtype, device:

some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.0956, 0.5737, 0.2314, 0.3674],
        [0.5690, 0.1331, 0.2764, 0.6825],
        [0.7503, 0.3797, 0.4045, 0.5101]])

In [220]:
some_tensor.shape

torch.Size([3, 4])

In [221]:
some_tensor.dtype

torch.float32

In [222]:
some_tensor.device

device(type='cpu')

In [223]:
#Manipulating tensors(tensor operations)
 #1. Addition
 #2. Substraction
 #3 Multiplication
 #4 Division
 #5 Matrix multiplication


In [224]:
#Addition
tensor= torch.tensor([1,2,3])
tensor

tensor([1, 2, 3])

In [225]:
tensor + 10

tensor([11, 12, 13])

In [226]:
tensor

tensor([1, 2, 3])

In [227]:
add= tensor + 10
add

tensor([11, 12, 13])

In [228]:
tensor_a= torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])


tensor_a + tensor_b


tensor([ 6,  8, 10, 12])

In [229]:
tensor_a= torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

torch.add(tensor_a, tensor_b)

tensor([ 6,  8, 10, 12])

In [233]:
#Substraction

sub_a_tensor = torch.tensor([1,2,3,4])
sub_b_tensor = ([5,6,7,8])
sub = (sub_a_tensor - 10)
sub




tensor([-9, -8, -7, -6])

In [236]:
#Multipalcation
mul_a = torch.tensor([1,2,3,4])
mul_b = torch.tensor([5,6,7,8])
mul = mul_a * mul_b
mul

tensor([ 5, 12, 21, 32])

In [237]:
mul1 =torch.mul(mul_a, mul_b)
mul1

tensor([ 5, 12, 21, 32])

In [238]:
#Tensor division
dev_a = torch.tensor([1,2,3,4])
dev_b = torch.tensor([5,6,7,8])
dev = dev_a / dev_b
dev


tensor([0.2000, 0.3333, 0.4286, 0.5000])

In [ ]:
#Tensor division
dev_a = torch.tensor([1,2,3,4])
dev_b = torch.tensor([5,6,7,8])
dev = dev_a / dev_b
dev